POST localhost:8080/api/v1/books/
Content-Type: application/json

{
  "id": 3,
  "title":"Title",
  "author":"Tlep"
}

###
POST localhost:8080/api/v1/rent/return/3

###
GET localhost:8080/api/v1/rent/debtors

###
GET localhost:8080/api/v1/rent/incomes

###
POST localhost:8080/api/v1/rent/2
Content-Type: application/json

{
  "id":  8,
  "user_id": 1,
  "duration": 1
}