// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/debtors": {
            "get": {
                "description": "get records of users with book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History of Book"
                ],
                "summary": "Debtors",
                "operationId": "Debtors",
                "parameters": [
                    {
                        "description": "history book info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HistoryBook"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/incomes": {
            "get": {
                "description": "get list of incomes of each books",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History of Book"
                ],
                "summary": "Incomes",
                "operationId": "Income",
                "parameters": [
                    {
                        "description": "incomes",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Income"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/rent": {
            "post": {
                "description": "create record about renting of book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History of Book"
                ],
                "summary": "Rent",
                "operationId": "Rent",
                "parameters": [
                    {
                        "description": "history book info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HistoryBook"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/return": {
            "post": {
                "description": "update record when user return book",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "History of Book"
                ],
                "summary": "Return",
                "operationId": "Return",
                "parameters": [
                    {
                        "description": "history book info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "model.HistoryBook": {
            "type": "object",
            "properties": {
                "bookID": {
                    "type": "integer"
                },
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "isGiven": {
                    "type": "boolean"
                },
                "isPaid": {
                    "type": "boolean"
                },
                "price": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.Income": {
            "type": "object",
            "properties": {
                "bookID": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "OneLab HomeWork API",
	Description:      "API service for User Storage.\nWhere they can create, retrieve, update, delete books.\nAnd can rent these books",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
